# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

ApplyCSold <- function(Number, kq, levelCon, noObs, a1, b1, a0, b0) {
    .Call('BayDR_ApplyCSold', PACKAGE = 'BayDR', Number, kq, levelCon, noObs, a1, b1, a0, b0)
}

ApplyCSoldhood <- function(Number, a1, b1, a0, b0) {
    .Call('BayDR_ApplyCSoldhood', PACKAGE = 'BayDR', Number, a1, b1, a0, b0)
}

CauEstC <- function(mcerror, gamma0, gamma1, gamma2, lambda1, lambda2, r, K, mean34) {
    .Call('BayDR_CauEstC', PACKAGE = 'BayDR', mcerror, gamma0, gamma1, gamma2, lambda1, lambda2, r, K, mean34)
}

Comb_C <- function(Comb, Number) {
    .Call('BayDR_Comb_C', PACKAGE = 'BayDR', Comb, Number)
}

DatDen_X_C <- function(C, phi0, phi1, phi2, lambda1, lambda2, K, No123, No1, No2, No34, Mean34) {
    .Call('BayDR_DatDen_X_C', PACKAGE = 'BayDR', C, phi0, phi1, phi2, lambda1, lambda2, K, No123, No1, No2, No34, Mean34)
}

EstS_C <- function(Comb1, Comb0, Number, kq, levelC, N) {
    .Call('BayDR_EstS_C', PACKAGE = 'BayDR', Comb1, Comb0, Number, kq, levelC, N)
}

Like_C <- function(Comb1, Comb0, Number) {
    .Call('BayDR_Like_C', PACKAGE = 'BayDR', Comb1, Comb0, Number)
}

Like_CBin <- function(Comb1, Comb0, Number) {
    .Call('BayDR_Like_CBin', PACKAGE = 'BayDR', Comb1, Comb0, Number)
}

NewComb_C <- function(Add, weight, Addbin, intMean, intCon) {
    .Call('BayDR_NewComb_C', PACKAGE = 'BayDR', Add, weight, Addbin, intMean, intCon)
}

